## 配置启动端口号
server:
  port: 8081
## 配置Mysql的基本信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mhweb?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
## jpa相关配置
  jpa:  
    ## 在处理请求时，将 EntityManager绑定到整个处理流程中
    open-in-view: true
    ## 当配置的值是 true的时候，允许在没有 transaction的情况下支持懒加载。
    properties:
      hibernate:
        ddl-auto: update
    show-sql: true